# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CashMarginUsed(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'object',
        'mtf': 'object',
        'loss': 'Loss',
        'span_exposure': 'object',
        'cash_margin_var_elm': 'object',
        'premium_present': 'object',
        'delivery_margin': 'DeliveryMargin'
    }

    attribute_map = {
        'total': 'total',
        'mtf': 'mtf',
        'loss': 'loss',
        'span_exposure': 'span_exposure',
        'cash_margin_var_elm': 'cash_margin_var_elm',
        'premium_present': 'premium_present',
        'delivery_margin': 'delivery_margin'
    }

    def __init__(self, total=None, mtf=None, loss=None, span_exposure=None, cash_margin_var_elm=None, premium_present=None, delivery_margin=None):  # noqa: E501
        """CashMarginUsed - a model defined in Swagger"""  # noqa: E501
        self._total = None
        self._mtf = None
        self._loss = None
        self._span_exposure = None
        self._cash_margin_var_elm = None
        self._premium_present = None
        self._delivery_margin = None
        self.discriminator = None
        if total is not None:
            self.total = total
        if mtf is not None:
            self.mtf = mtf
        if loss is not None:
            self.loss = loss
        if span_exposure is not None:
            self.span_exposure = span_exposure
        if cash_margin_var_elm is not None:
            self.cash_margin_var_elm = cash_margin_var_elm
        if premium_present is not None:
            self.premium_present = premium_present
        if delivery_margin is not None:
            self.delivery_margin = delivery_margin

    @property
    def total(self):
        """Gets the total of this CashMarginUsed.  # noqa: E501


        :return: The total of this CashMarginUsed.  # noqa: E501
        :rtype: object
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this CashMarginUsed.


        :param total: The total of this CashMarginUsed.  # noqa: E501
        :type: object
        """

        self._total = total

    @property
    def mtf(self):
        """Gets the mtf of this CashMarginUsed.  # noqa: E501


        :return: The mtf of this CashMarginUsed.  # noqa: E501
        :rtype: object
        """
        return self._mtf

    @mtf.setter
    def mtf(self, mtf):
        """Sets the mtf of this CashMarginUsed.


        :param mtf: The mtf of this CashMarginUsed.  # noqa: E501
        :type: object
        """

        self._mtf = mtf

    @property
    def loss(self):
        """Gets the loss of this CashMarginUsed.  # noqa: E501


        :return: The loss of this CashMarginUsed.  # noqa: E501
        :rtype: Loss
        """
        return self._loss

    @loss.setter
    def loss(self, loss):
        """Sets the loss of this CashMarginUsed.


        :param loss: The loss of this CashMarginUsed.  # noqa: E501
        :type: Loss
        """

        self._loss = loss

    @property
    def span_exposure(self):
        """Gets the span_exposure of this CashMarginUsed.  # noqa: E501


        :return: The span_exposure of this CashMarginUsed.  # noqa: E501
        :rtype: object
        """
        return self._span_exposure

    @span_exposure.setter
    def span_exposure(self, span_exposure):
        """Sets the span_exposure of this CashMarginUsed.


        :param span_exposure: The span_exposure of this CashMarginUsed.  # noqa: E501
        :type: object
        """

        self._span_exposure = span_exposure

    @property
    def cash_margin_var_elm(self):
        """Gets the cash_margin_var_elm of this CashMarginUsed.  # noqa: E501


        :return: The cash_margin_var_elm of this CashMarginUsed.  # noqa: E501
        :rtype: object
        """
        return self._cash_margin_var_elm

    @cash_margin_var_elm.setter
    def cash_margin_var_elm(self, cash_margin_var_elm):
        """Sets the cash_margin_var_elm of this CashMarginUsed.


        :param cash_margin_var_elm: The cash_margin_var_elm of this CashMarginUsed.  # noqa: E501
        :type: object
        """

        self._cash_margin_var_elm = cash_margin_var_elm

    @property
    def premium_present(self):
        """Gets the premium_present of this CashMarginUsed.  # noqa: E501


        :return: The premium_present of this CashMarginUsed.  # noqa: E501
        :rtype: object
        """
        return self._premium_present

    @premium_present.setter
    def premium_present(self, premium_present):
        """Sets the premium_present of this CashMarginUsed.


        :param premium_present: The premium_present of this CashMarginUsed.  # noqa: E501
        :type: object
        """

        self._premium_present = premium_present

    @property
    def delivery_margin(self):
        """Gets the delivery_margin of this CashMarginUsed.  # noqa: E501


        :return: The delivery_margin of this CashMarginUsed.  # noqa: E501
        :rtype: DeliveryMargin
        """
        return self._delivery_margin

    @delivery_margin.setter
    def delivery_margin(self, delivery_margin):
        """Sets the delivery_margin of this CashMarginUsed.


        :param delivery_margin: The delivery_margin of this CashMarginUsed.  # noqa: E501
        :type: DeliveryMargin
        """

        self._delivery_margin = delivery_margin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CashMarginUsed, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CashMarginUsed):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
