# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CashUnavailableToTrade(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unsettled_profit': 'UnsettledProfit'
    }

    attribute_map = {
        'unsettled_profit': 'unsettled_profit'
    }

    def __init__(self, unsettled_profit=None):  # noqa: E501
        """CashUnavailableToTrade - a model defined in Swagger"""  # noqa: E501
        self._unsettled_profit = None
        self.discriminator = None
        if unsettled_profit is not None:
            self.unsettled_profit = unsettled_profit

    @property
    def unsettled_profit(self):
        """Gets the unsettled_profit of this CashUnavailableToTrade.  # noqa: E501


        :return: The unsettled_profit of this CashUnavailableToTrade.  # noqa: E501
        :rtype: UnsettledProfit
        """
        return self._unsettled_profit

    @unsettled_profit.setter
    def unsettled_profit(self, unsettled_profit):
        """Sets the unsettled_profit of this CashUnavailableToTrade.


        :param unsettled_profit: The unsettled_profit of this CashUnavailableToTrade.  # noqa: E501
        :type: UnsettledProfit
        """

        self._unsettled_profit = unsettled_profit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CashUnavailableToTrade, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CashUnavailableToTrade):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
