# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GttTriggerOrderResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'data': 'GttOrderData',
        'metadata': 'OrderMetadata'
    }

    attribute_map = {
        'status': 'status',
        'data': 'data',
        'metadata': 'metadata'
    }

    def __init__(self, status=None, data=None, metadata=None):  # noqa: E501
        """GttTriggerOrderResponse - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._data = None
        self._metadata = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if data is not None:
            self.data = data
        if metadata is not None:
            self.metadata = metadata

    @property
    def status(self):
        """Gets the status of this GttTriggerOrderResponse.  # noqa: E501


        :return: The status of this GttTriggerOrderResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this GttTriggerOrderResponse.


        :param status: The status of this GttTriggerOrderResponse.  # noqa: E501
        :type: str
        """
        allowed_values = ["success", "error", "partial_success"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def data(self):
        """Gets the data of this GttTriggerOrderResponse.  # noqa: E501


        :return: The data of this GttTriggerOrderResponse.  # noqa: E501
        :rtype: GttOrderData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GttTriggerOrderResponse.


        :param data: The data of this GttTriggerOrderResponse.  # noqa: E501
        :type: GttOrderData
        """

        self._data = data

    @property
    def metadata(self):
        """Gets the metadata of this GttTriggerOrderResponse.  # noqa: E501


        :return: The metadata of this GttTriggerOrderResponse.  # noqa: E501
        :rtype: OrderMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this GttTriggerOrderResponse.


        :param metadata: The metadata of this GttTriggerOrderResponse.  # noqa: E501
        :type: OrderMetadata
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GttTriggerOrderResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GttTriggerOrderResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
