# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InitiatePayoutRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mode': 'object',
        'amount': 'object'
    }

    attribute_map = {
        'mode': 'mode',
        'amount': 'amount'
    }

    def __init__(self, mode=None, amount=None):  # noqa: E501
        """InitiatePayoutRequest - a model defined in Swagger"""  # noqa: E501
        self._mode = None
        self._amount = None
        self.discriminator = None
        self.mode = mode
        self.amount = amount

    @property
    def mode(self):
        """Gets the mode of this InitiatePayoutRequest.  # noqa: E501

        Withdrawal mode. NEFT or IMPS  # noqa: E501

        :return: The mode of this InitiatePayoutRequest.  # noqa: E501
        :rtype: object
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this InitiatePayoutRequest.

        Withdrawal mode. NEFT or IMPS  # noqa: E501

        :param mode: The mode of this InitiatePayoutRequest.  # noqa: E501
        :type: object
        """
        if mode is None:
            raise ValueError("Invalid value for `mode`, must not be `None`")  # noqa: E501

        self._mode = mode

    @property
    def amount(self):
        """Gets the amount of this InitiatePayoutRequest.  # noqa: E501

        Withdrawal amount in INR  # noqa: E501

        :return: The amount of this InitiatePayoutRequest.  # noqa: E501
        :rtype: object
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this InitiatePayoutRequest.

        Withdrawal amount in INR  # noqa: E501

        :param amount: The amount of this InitiatePayoutRequest.  # noqa: E501
        :type: object
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InitiatePayoutRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InitiatePayoutRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
