# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IpoDetailsData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'symbol': 'object',
        'name': 'object',
        'status': 'object',
        'isin': 'object',
        'issue_type': 'object',
        'issue_size': 'object',
        'industry': 'object',
        'minimum_price': 'object',
        'maximum_price': 'object',
        'bidding_start_date': 'object',
        'bidding_end_date': 'object',
        'daily_start_time': 'object',
        'daily_end_time': 'object',
        'face_value': 'object',
        'tick_size': 'object',
        'lot_size': 'object',
        'minimum_quantity': 'object',
        'cut_off_price': 'object',
        'listing_price': 'object',
        'listing_exchange': 'object',
        'rhp_url': 'object',
        'drhp_url': 'object',
        'timeline': 'IpoTimeline',
        'registrar_info': 'IpoRegistrarInfo',
        'total_subscription': 'object'
    }

    attribute_map = {
        'id': 'id',
        'symbol': 'symbol',
        'name': 'name',
        'status': 'status',
        'isin': 'isin',
        'issue_type': 'issue_type',
        'issue_size': 'issue_size',
        'industry': 'industry',
        'minimum_price': 'minimum_price',
        'maximum_price': 'maximum_price',
        'bidding_start_date': 'bidding_start_date',
        'bidding_end_date': 'bidding_end_date',
        'daily_start_time': 'daily_start_time',
        'daily_end_time': 'daily_end_time',
        'face_value': 'face_value',
        'tick_size': 'tick_size',
        'lot_size': 'lot_size',
        'minimum_quantity': 'minimum_quantity',
        'cut_off_price': 'cut_off_price',
        'listing_price': 'listing_price',
        'listing_exchange': 'listing_exchange',
        'rhp_url': 'rhp_url',
        'drhp_url': 'drhp_url',
        'timeline': 'timeline',
        'registrar_info': 'registrar_info',
        'total_subscription': 'total_subscription'
    }

    def __init__(self, id=None, symbol=None, name=None, status=None, isin=None, issue_type=None, issue_size=None, industry=None, minimum_price=None, maximum_price=None, bidding_start_date=None, bidding_end_date=None, daily_start_time=None, daily_end_time=None, face_value=None, tick_size=None, lot_size=None, minimum_quantity=None, cut_off_price=None, listing_price=None, listing_exchange=None, rhp_url=None, drhp_url=None, timeline=None, registrar_info=None, total_subscription=None):  # noqa: E501
        """IpoDetailsData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._symbol = None
        self._name = None
        self._status = None
        self._isin = None
        self._issue_type = None
        self._issue_size = None
        self._industry = None
        self._minimum_price = None
        self._maximum_price = None
        self._bidding_start_date = None
        self._bidding_end_date = None
        self._daily_start_time = None
        self._daily_end_time = None
        self._face_value = None
        self._tick_size = None
        self._lot_size = None
        self._minimum_quantity = None
        self._cut_off_price = None
        self._listing_price = None
        self._listing_exchange = None
        self._rhp_url = None
        self._drhp_url = None
        self._timeline = None
        self._registrar_info = None
        self._total_subscription = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if symbol is not None:
            self.symbol = symbol
        if name is not None:
            self.name = name
        if status is not None:
            self.status = status
        if isin is not None:
            self.isin = isin
        if issue_type is not None:
            self.issue_type = issue_type
        if issue_size is not None:
            self.issue_size = issue_size
        if industry is not None:
            self.industry = industry
        if minimum_price is not None:
            self.minimum_price = minimum_price
        if maximum_price is not None:
            self.maximum_price = maximum_price
        if bidding_start_date is not None:
            self.bidding_start_date = bidding_start_date
        if bidding_end_date is not None:
            self.bidding_end_date = bidding_end_date
        if daily_start_time is not None:
            self.daily_start_time = daily_start_time
        if daily_end_time is not None:
            self.daily_end_time = daily_end_time
        if face_value is not None:
            self.face_value = face_value
        if tick_size is not None:
            self.tick_size = tick_size
        if lot_size is not None:
            self.lot_size = lot_size
        if minimum_quantity is not None:
            self.minimum_quantity = minimum_quantity
        if cut_off_price is not None:
            self.cut_off_price = cut_off_price
        if listing_price is not None:
            self.listing_price = listing_price
        if listing_exchange is not None:
            self.listing_exchange = listing_exchange
        if rhp_url is not None:
            self.rhp_url = rhp_url
        if drhp_url is not None:
            self.drhp_url = drhp_url
        if timeline is not None:
            self.timeline = timeline
        if registrar_info is not None:
            self.registrar_info = registrar_info
        if total_subscription is not None:
            self.total_subscription = total_subscription

    @property
    def id(self):
        """Gets the id of this IpoDetailsData.  # noqa: E501


        :return: The id of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IpoDetailsData.


        :param id: The id of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def symbol(self):
        """Gets the symbol of this IpoDetailsData.  # noqa: E501


        :return: The symbol of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this IpoDetailsData.


        :param symbol: The symbol of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._symbol = symbol

    @property
    def name(self):
        """Gets the name of this IpoDetailsData.  # noqa: E501


        :return: The name of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IpoDetailsData.


        :param name: The name of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this IpoDetailsData.  # noqa: E501


        :return: The status of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this IpoDetailsData.


        :param status: The status of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._status = status

    @property
    def isin(self):
        """Gets the isin of this IpoDetailsData.  # noqa: E501


        :return: The isin of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._isin

    @isin.setter
    def isin(self, isin):
        """Sets the isin of this IpoDetailsData.


        :param isin: The isin of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._isin = isin

    @property
    def issue_type(self):
        """Gets the issue_type of this IpoDetailsData.  # noqa: E501


        :return: The issue_type of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._issue_type

    @issue_type.setter
    def issue_type(self, issue_type):
        """Sets the issue_type of this IpoDetailsData.


        :param issue_type: The issue_type of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._issue_type = issue_type

    @property
    def issue_size(self):
        """Gets the issue_size of this IpoDetailsData.  # noqa: E501


        :return: The issue_size of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._issue_size

    @issue_size.setter
    def issue_size(self, issue_size):
        """Sets the issue_size of this IpoDetailsData.


        :param issue_size: The issue_size of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._issue_size = issue_size

    @property
    def industry(self):
        """Gets the industry of this IpoDetailsData.  # noqa: E501


        :return: The industry of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._industry

    @industry.setter
    def industry(self, industry):
        """Sets the industry of this IpoDetailsData.


        :param industry: The industry of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._industry = industry

    @property
    def minimum_price(self):
        """Gets the minimum_price of this IpoDetailsData.  # noqa: E501


        :return: The minimum_price of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._minimum_price

    @minimum_price.setter
    def minimum_price(self, minimum_price):
        """Sets the minimum_price of this IpoDetailsData.


        :param minimum_price: The minimum_price of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._minimum_price = minimum_price

    @property
    def maximum_price(self):
        """Gets the maximum_price of this IpoDetailsData.  # noqa: E501


        :return: The maximum_price of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._maximum_price

    @maximum_price.setter
    def maximum_price(self, maximum_price):
        """Sets the maximum_price of this IpoDetailsData.


        :param maximum_price: The maximum_price of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._maximum_price = maximum_price

    @property
    def bidding_start_date(self):
        """Gets the bidding_start_date of this IpoDetailsData.  # noqa: E501


        :return: The bidding_start_date of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._bidding_start_date

    @bidding_start_date.setter
    def bidding_start_date(self, bidding_start_date):
        """Sets the bidding_start_date of this IpoDetailsData.


        :param bidding_start_date: The bidding_start_date of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._bidding_start_date = bidding_start_date

    @property
    def bidding_end_date(self):
        """Gets the bidding_end_date of this IpoDetailsData.  # noqa: E501


        :return: The bidding_end_date of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._bidding_end_date

    @bidding_end_date.setter
    def bidding_end_date(self, bidding_end_date):
        """Sets the bidding_end_date of this IpoDetailsData.


        :param bidding_end_date: The bidding_end_date of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._bidding_end_date = bidding_end_date

    @property
    def daily_start_time(self):
        """Gets the daily_start_time of this IpoDetailsData.  # noqa: E501


        :return: The daily_start_time of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._daily_start_time

    @daily_start_time.setter
    def daily_start_time(self, daily_start_time):
        """Sets the daily_start_time of this IpoDetailsData.


        :param daily_start_time: The daily_start_time of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._daily_start_time = daily_start_time

    @property
    def daily_end_time(self):
        """Gets the daily_end_time of this IpoDetailsData.  # noqa: E501


        :return: The daily_end_time of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._daily_end_time

    @daily_end_time.setter
    def daily_end_time(self, daily_end_time):
        """Sets the daily_end_time of this IpoDetailsData.


        :param daily_end_time: The daily_end_time of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._daily_end_time = daily_end_time

    @property
    def face_value(self):
        """Gets the face_value of this IpoDetailsData.  # noqa: E501


        :return: The face_value of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._face_value

    @face_value.setter
    def face_value(self, face_value):
        """Sets the face_value of this IpoDetailsData.


        :param face_value: The face_value of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._face_value = face_value

    @property
    def tick_size(self):
        """Gets the tick_size of this IpoDetailsData.  # noqa: E501


        :return: The tick_size of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._tick_size

    @tick_size.setter
    def tick_size(self, tick_size):
        """Sets the tick_size of this IpoDetailsData.


        :param tick_size: The tick_size of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._tick_size = tick_size

    @property
    def lot_size(self):
        """Gets the lot_size of this IpoDetailsData.  # noqa: E501


        :return: The lot_size of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._lot_size

    @lot_size.setter
    def lot_size(self, lot_size):
        """Sets the lot_size of this IpoDetailsData.


        :param lot_size: The lot_size of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._lot_size = lot_size

    @property
    def minimum_quantity(self):
        """Gets the minimum_quantity of this IpoDetailsData.  # noqa: E501


        :return: The minimum_quantity of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._minimum_quantity

    @minimum_quantity.setter
    def minimum_quantity(self, minimum_quantity):
        """Sets the minimum_quantity of this IpoDetailsData.


        :param minimum_quantity: The minimum_quantity of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._minimum_quantity = minimum_quantity

    @property
    def cut_off_price(self):
        """Gets the cut_off_price of this IpoDetailsData.  # noqa: E501


        :return: The cut_off_price of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._cut_off_price

    @cut_off_price.setter
    def cut_off_price(self, cut_off_price):
        """Sets the cut_off_price of this IpoDetailsData.


        :param cut_off_price: The cut_off_price of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._cut_off_price = cut_off_price

    @property
    def listing_price(self):
        """Gets the listing_price of this IpoDetailsData.  # noqa: E501


        :return: The listing_price of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._listing_price

    @listing_price.setter
    def listing_price(self, listing_price):
        """Sets the listing_price of this IpoDetailsData.


        :param listing_price: The listing_price of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._listing_price = listing_price

    @property
    def listing_exchange(self):
        """Gets the listing_exchange of this IpoDetailsData.  # noqa: E501


        :return: The listing_exchange of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._listing_exchange

    @listing_exchange.setter
    def listing_exchange(self, listing_exchange):
        """Sets the listing_exchange of this IpoDetailsData.


        :param listing_exchange: The listing_exchange of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._listing_exchange = listing_exchange

    @property
    def rhp_url(self):
        """Gets the rhp_url of this IpoDetailsData.  # noqa: E501


        :return: The rhp_url of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._rhp_url

    @rhp_url.setter
    def rhp_url(self, rhp_url):
        """Sets the rhp_url of this IpoDetailsData.


        :param rhp_url: The rhp_url of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._rhp_url = rhp_url

    @property
    def drhp_url(self):
        """Gets the drhp_url of this IpoDetailsData.  # noqa: E501


        :return: The drhp_url of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._drhp_url

    @drhp_url.setter
    def drhp_url(self, drhp_url):
        """Sets the drhp_url of this IpoDetailsData.


        :param drhp_url: The drhp_url of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._drhp_url = drhp_url

    @property
    def timeline(self):
        """Gets the timeline of this IpoDetailsData.  # noqa: E501


        :return: The timeline of this IpoDetailsData.  # noqa: E501
        :rtype: IpoTimeline
        """
        return self._timeline

    @timeline.setter
    def timeline(self, timeline):
        """Sets the timeline of this IpoDetailsData.


        :param timeline: The timeline of this IpoDetailsData.  # noqa: E501
        :type: IpoTimeline
        """

        self._timeline = timeline

    @property
    def registrar_info(self):
        """Gets the registrar_info of this IpoDetailsData.  # noqa: E501


        :return: The registrar_info of this IpoDetailsData.  # noqa: E501
        :rtype: IpoRegistrarInfo
        """
        return self._registrar_info

    @registrar_info.setter
    def registrar_info(self, registrar_info):
        """Sets the registrar_info of this IpoDetailsData.


        :param registrar_info: The registrar_info of this IpoDetailsData.  # noqa: E501
        :type: IpoRegistrarInfo
        """

        self._registrar_info = registrar_info

    @property
    def total_subscription(self):
        """Gets the total_subscription of this IpoDetailsData.  # noqa: E501


        :return: The total_subscription of this IpoDetailsData.  # noqa: E501
        :rtype: object
        """
        return self._total_subscription

    @total_subscription.setter
    def total_subscription(self, total_subscription):
        """Sets the total_subscription of this IpoDetailsData.


        :param total_subscription: The total_subscription of this IpoDetailsData.  # noqa: E501
        :type: object
        """

        self._total_subscription = total_subscription

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IpoDetailsData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IpoDetailsData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
