# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IpoOrderBid(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quantity': 'object',
        'price': 'object',
        'amount': 'object',
        'message': 'object'
    }

    attribute_map = {
        'quantity': 'quantity',
        'price': 'price',
        'amount': 'amount',
        'message': 'message'
    }

    def __init__(self, quantity=None, price=None, amount=None, message=None):  # noqa: E501
        """IpoOrderBid - a model defined in Swagger"""  # noqa: E501
        self._quantity = None
        self._price = None
        self._amount = None
        self._message = None
        self.discriminator = None
        if quantity is not None:
            self.quantity = quantity
        if price is not None:
            self.price = price
        if amount is not None:
            self.amount = amount
        if message is not None:
            self.message = message

    @property
    def quantity(self):
        """Gets the quantity of this IpoOrderBid.  # noqa: E501

        Number of shares bid for  # noqa: E501

        :return: The quantity of this IpoOrderBid.  # noqa: E501
        :rtype: object
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this IpoOrderBid.

        Number of shares bid for  # noqa: E501

        :param quantity: The quantity of this IpoOrderBid.  # noqa: E501
        :type: object
        """

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this IpoOrderBid.  # noqa: E501

        Bid price per share  # noqa: E501

        :return: The price of this IpoOrderBid.  # noqa: E501
        :rtype: object
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this IpoOrderBid.

        Bid price per share  # noqa: E501

        :param price: The price of this IpoOrderBid.  # noqa: E501
        :type: object
        """

        self._price = price

    @property
    def amount(self):
        """Gets the amount of this IpoOrderBid.  # noqa: E501

        Value of the bid, quantity x price  # noqa: E501

        :return: The amount of this IpoOrderBid.  # noqa: E501
        :rtype: object
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this IpoOrderBid.

        Value of the bid, quantity x price  # noqa: E501

        :param amount: The amount of this IpoOrderBid.  # noqa: E501
        :type: object
        """

        self._amount = amount

    @property
    def message(self):
        """Gets the message of this IpoOrderBid.  # noqa: E501

        Message from the exchange for this bid, when one was returned  # noqa: E501

        :return: The message of this IpoOrderBid.  # noqa: E501
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this IpoOrderBid.

        Message from the exchange for this bid, when one was returned  # noqa: E501

        :param message: The message of this IpoOrderBid.  # noqa: E501
        :type: object
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IpoOrderBid, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IpoOrderBid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
