# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KillSwitchSegmentData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'segment': 'object',
        'segment_status': 'object',
        'kill_switch_enabled': 'object'
    }

    attribute_map = {
        'segment': 'segment',
        'segment_status': 'segment_status',
        'kill_switch_enabled': 'kill_switch_enabled'
    }

    def __init__(self, segment=None, segment_status=None, kill_switch_enabled=None):  # noqa: E501
        """KillSwitchSegmentData - a model defined in Swagger"""  # noqa: E501
        self._segment = None
        self._segment_status = None
        self._kill_switch_enabled = None
        self.discriminator = None
        if segment is not None:
            self.segment = segment
        if segment_status is not None:
            self.segment_status = segment_status
        if kill_switch_enabled is not None:
            self.kill_switch_enabled = kill_switch_enabled

    @property
    def segment(self):
        """Gets the segment of this KillSwitchSegmentData.  # noqa: E501


        :return: The segment of this KillSwitchSegmentData.  # noqa: E501
        :rtype: object
        """
        return self._segment

    @segment.setter
    def segment(self, segment):
        """Sets the segment of this KillSwitchSegmentData.


        :param segment: The segment of this KillSwitchSegmentData.  # noqa: E501
        :type: object
        """

        self._segment = segment

    @property
    def segment_status(self):
        """Gets the segment_status of this KillSwitchSegmentData.  # noqa: E501


        :return: The segment_status of this KillSwitchSegmentData.  # noqa: E501
        :rtype: object
        """
        return self._segment_status

    @segment_status.setter
    def segment_status(self, segment_status):
        """Sets the segment_status of this KillSwitchSegmentData.


        :param segment_status: The segment_status of this KillSwitchSegmentData.  # noqa: E501
        :type: object
        """

        self._segment_status = segment_status

    @property
    def kill_switch_enabled(self):
        """Gets the kill_switch_enabled of this KillSwitchSegmentData.  # noqa: E501


        :return: The kill_switch_enabled of this KillSwitchSegmentData.  # noqa: E501
        :rtype: object
        """
        return self._kill_switch_enabled

    @kill_switch_enabled.setter
    def kill_switch_enabled(self, kill_switch_enabled):
        """Sets the kill_switch_enabled of this KillSwitchSegmentData.


        :param kill_switch_enabled: The kill_switch_enabled of this KillSwitchSegmentData.  # noqa: E501
        :type: object
        """

        self._kill_switch_enabled = kill_switch_enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KillSwitchSegmentData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KillSwitchSegmentData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
