# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MarketQuoteOHLCV3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'last_price': 'float',
        'instrument_token': 'str',
        'prev_ohlc': 'OhlcV3',
        'live_ohlc': 'OhlcV3'
    }

    attribute_map = {
        'last_price': 'last_price',
        'instrument_token': 'instrument_token',
        'prev_ohlc': 'prev_ohlc',
        'live_ohlc': 'live_ohlc'
    }

    def __init__(self, last_price=None, instrument_token=None, prev_ohlc=None, live_ohlc=None):  # noqa: E501
        """MarketQuoteOHLCV3 - a model defined in Swagger"""  # noqa: E501
        self._last_price = None
        self._instrument_token = None
        self._prev_ohlc = None
        self._live_ohlc = None
        self.discriminator = None
        if last_price is not None:
            self.last_price = last_price
        if instrument_token is not None:
            self.instrument_token = instrument_token
        if prev_ohlc is not None:
            self.prev_ohlc = prev_ohlc
        if live_ohlc is not None:
            self.live_ohlc = live_ohlc

    @property
    def last_price(self):
        """Gets the last_price of this MarketQuoteOHLCV3.  # noqa: E501

        The last traded price of symbol  # noqa: E501

        :return: The last_price of this MarketQuoteOHLCV3.  # noqa: E501
        :rtype: float
        """
        return self._last_price

    @last_price.setter
    def last_price(self, last_price):
        """Sets the last_price of this MarketQuoteOHLCV3.

        The last traded price of symbol  # noqa: E501

        :param last_price: The last_price of this MarketQuoteOHLCV3.  # noqa: E501
        :type: float
        """

        self._last_price = last_price

    @property
    def instrument_token(self):
        """Gets the instrument_token of this MarketQuoteOHLCV3.  # noqa: E501


        :return: The instrument_token of this MarketQuoteOHLCV3.  # noqa: E501
        :rtype: str
        """
        return self._instrument_token

    @instrument_token.setter
    def instrument_token(self, instrument_token):
        """Sets the instrument_token of this MarketQuoteOHLCV3.


        :param instrument_token: The instrument_token of this MarketQuoteOHLCV3.  # noqa: E501
        :type: str
        """

        self._instrument_token = instrument_token

    @property
    def prev_ohlc(self):
        """Gets the prev_ohlc of this MarketQuoteOHLCV3.  # noqa: E501


        :return: The prev_ohlc of this MarketQuoteOHLCV3.  # noqa: E501
        :rtype: OhlcV3
        """
        return self._prev_ohlc

    @prev_ohlc.setter
    def prev_ohlc(self, prev_ohlc):
        """Sets the prev_ohlc of this MarketQuoteOHLCV3.


        :param prev_ohlc: The prev_ohlc of this MarketQuoteOHLCV3.  # noqa: E501
        :type: OhlcV3
        """

        self._prev_ohlc = prev_ohlc

    @property
    def live_ohlc(self):
        """Gets the live_ohlc of this MarketQuoteOHLCV3.  # noqa: E501


        :return: The live_ohlc of this MarketQuoteOHLCV3.  # noqa: E501
        :rtype: OhlcV3
        """
        return self._live_ohlc

    @live_ohlc.setter
    def live_ohlc(self, live_ohlc):
        """Sets the live_ohlc of this MarketQuoteOHLCV3.


        :param live_ohlc: The live_ohlc of this MarketQuoteOHLCV3.  # noqa: E501
        :type: OhlcV3
        """

        self._live_ohlc = live_ohlc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MarketQuoteOHLCV3, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarketQuoteOHLCV3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
