# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MutualFundSipData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fund': 'object',
        'status': 'object',
        'created': 'object',
        'frequency': 'object',
        'instalments': 'object',
        'sip_id': 'object',
        'sip_reg_number': 'object',
        'instrument_key': 'object',
        'dividend_type': 'object',
        'transaction_type': 'object',
        'next_instalment': 'object',
        'instalment_amount': 'object',
        'last_instalment': 'object',
        'pending_instalments': 'object',
        'instalment_day': 'object',
        'completed_instalments': 'object',
        'trigger_price': 'object',
        'sip_type': 'object'
    }

    attribute_map = {
        'fund': 'fund',
        'status': 'status',
        'created': 'created',
        'frequency': 'frequency',
        'instalments': 'instalments',
        'sip_id': 'sip_id',
        'sip_reg_number': 'sip_reg_number',
        'instrument_key': 'instrument_key',
        'dividend_type': 'dividend_type',
        'transaction_type': 'transaction_type',
        'next_instalment': 'next_instalment',
        'instalment_amount': 'instalment_amount',
        'last_instalment': 'last_instalment',
        'pending_instalments': 'pending_instalments',
        'instalment_day': 'instalment_day',
        'completed_instalments': 'completed_instalments',
        'trigger_price': 'trigger_price',
        'sip_type': 'sip_type'
    }

    def __init__(self, fund=None, status=None, created=None, frequency=None, instalments=None, sip_id=None, sip_reg_number=None, instrument_key=None, dividend_type=None, transaction_type=None, next_instalment=None, instalment_amount=None, last_instalment=None, pending_instalments=None, instalment_day=None, completed_instalments=None, trigger_price=None, sip_type=None):  # noqa: E501
        """MutualFundSipData - a model defined in Swagger"""  # noqa: E501
        self._fund = None
        self._status = None
        self._created = None
        self._frequency = None
        self._instalments = None
        self._sip_id = None
        self._sip_reg_number = None
        self._instrument_key = None
        self._dividend_type = None
        self._transaction_type = None
        self._next_instalment = None
        self._instalment_amount = None
        self._last_instalment = None
        self._pending_instalments = None
        self._instalment_day = None
        self._completed_instalments = None
        self._trigger_price = None
        self._sip_type = None
        self.discriminator = None
        if fund is not None:
            self.fund = fund
        if status is not None:
            self.status = status
        if created is not None:
            self.created = created
        if frequency is not None:
            self.frequency = frequency
        if instalments is not None:
            self.instalments = instalments
        if sip_id is not None:
            self.sip_id = sip_id
        if sip_reg_number is not None:
            self.sip_reg_number = sip_reg_number
        if instrument_key is not None:
            self.instrument_key = instrument_key
        if dividend_type is not None:
            self.dividend_type = dividend_type
        if transaction_type is not None:
            self.transaction_type = transaction_type
        if next_instalment is not None:
            self.next_instalment = next_instalment
        if instalment_amount is not None:
            self.instalment_amount = instalment_amount
        if last_instalment is not None:
            self.last_instalment = last_instalment
        if pending_instalments is not None:
            self.pending_instalments = pending_instalments
        if instalment_day is not None:
            self.instalment_day = instalment_day
        if completed_instalments is not None:
            self.completed_instalments = completed_instalments
        if trigger_price is not None:
            self.trigger_price = trigger_price
        if sip_type is not None:
            self.sip_type = sip_type

    @property
    def fund(self):
        """Gets the fund of this MutualFundSipData.  # noqa: E501

        Display name of the fund.  # noqa: E501

        :return: The fund of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._fund

    @fund.setter
    def fund(self, fund):
        """Sets the fund of this MutualFundSipData.

        Display name of the fund.  # noqa: E501

        :param fund: The fund of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._fund = fund

    @property
    def status(self):
        """Gets the status of this MutualFundSipData.  # noqa: E501

        ACTIVE, PAUSED, or CANCELLED.  # noqa: E501

        :return: The status of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MutualFundSipData.

        ACTIVE, PAUSED, or CANCELLED.  # noqa: E501

        :param status: The status of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._status = status

    @property
    def created(self):
        """Gets the created of this MutualFundSipData.  # noqa: E501

        Timestamp when the SIP was registered.  # noqa: E501

        :return: The created of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this MutualFundSipData.

        Timestamp when the SIP was registered.  # noqa: E501

        :param created: The created of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._created = created

    @property
    def frequency(self):
        """Gets the frequency of this MutualFundSipData.  # noqa: E501

        Frequency (e.g. monthly, weekly).  # noqa: E501

        :return: The frequency of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this MutualFundSipData.

        Frequency (e.g. monthly, weekly).  # noqa: E501

        :param frequency: The frequency of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._frequency = frequency

    @property
    def instalments(self):
        """Gets the instalments of this MutualFundSipData.  # noqa: E501

        Total number of instalments when applicable; -1 if open-ended.  # noqa: E501

        :return: The instalments of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._instalments

    @instalments.setter
    def instalments(self, instalments):
        """Sets the instalments of this MutualFundSipData.

        Total number of instalments when applicable; -1 if open-ended.  # noqa: E501

        :param instalments: The instalments of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._instalments = instalments

    @property
    def sip_id(self):
        """Gets the sip_id of this MutualFundSipData.  # noqa: E501

        Unique SIP identifier.  # noqa: E501

        :return: The sip_id of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._sip_id

    @sip_id.setter
    def sip_id(self, sip_id):
        """Sets the sip_id of this MutualFundSipData.

        Unique SIP identifier.  # noqa: E501

        :param sip_id: The sip_id of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._sip_id = sip_id

    @property
    def sip_reg_number(self):
        """Gets the sip_reg_number of this MutualFundSipData.  # noqa: E501

        SIP registration number when available.  # noqa: E501

        :return: The sip_reg_number of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._sip_reg_number

    @sip_reg_number.setter
    def sip_reg_number(self, sip_reg_number):
        """Sets the sip_reg_number of this MutualFundSipData.

        SIP registration number when available.  # noqa: E501

        :param sip_reg_number: The sip_reg_number of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._sip_reg_number = sip_reg_number

    @property
    def instrument_key(self):
        """Gets the instrument_key of this MutualFundSipData.  # noqa: E501

        ISIN of the fund, when available.  # noqa: E501

        :return: The instrument_key of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._instrument_key

    @instrument_key.setter
    def instrument_key(self, instrument_key):
        """Sets the instrument_key of this MutualFundSipData.

        ISIN of the fund, when available.  # noqa: E501

        :param instrument_key: The instrument_key of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._instrument_key = instrument_key

    @property
    def dividend_type(self):
        """Gets the dividend_type of this MutualFundSipData.  # noqa: E501

        Dividend option when available (e.g. growth, idcw).  # noqa: E501

        :return: The dividend_type of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._dividend_type

    @dividend_type.setter
    def dividend_type(self, dividend_type):
        """Sets the dividend_type of this MutualFundSipData.

        Dividend option when available (e.g. growth, idcw).  # noqa: E501

        :param dividend_type: The dividend_type of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._dividend_type = dividend_type

    @property
    def transaction_type(self):
        """Gets the transaction_type of this MutualFundSipData.  # noqa: E501

        BUY or SELL.  # noqa: E501

        :return: The transaction_type of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._transaction_type

    @transaction_type.setter
    def transaction_type(self, transaction_type):
        """Sets the transaction_type of this MutualFundSipData.

        BUY or SELL.  # noqa: E501

        :param transaction_type: The transaction_type of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._transaction_type = transaction_type

    @property
    def next_instalment(self):
        """Gets the next_instalment of this MutualFundSipData.  # noqa: E501

        Next instalment date.  # noqa: E501

        :return: The next_instalment of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._next_instalment

    @next_instalment.setter
    def next_instalment(self, next_instalment):
        """Sets the next_instalment of this MutualFundSipData.

        Next instalment date.  # noqa: E501

        :param next_instalment: The next_instalment of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._next_instalment = next_instalment

    @property
    def instalment_amount(self):
        """Gets the instalment_amount of this MutualFundSipData.  # noqa: E501

        Amount per instalment.  # noqa: E501

        :return: The instalment_amount of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._instalment_amount

    @instalment_amount.setter
    def instalment_amount(self, instalment_amount):
        """Sets the instalment_amount of this MutualFundSipData.

        Amount per instalment.  # noqa: E501

        :param instalment_amount: The instalment_amount of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._instalment_amount = instalment_amount

    @property
    def last_instalment(self):
        """Gets the last_instalment of this MutualFundSipData.  # noqa: E501

        Last triggered instalment timestamp.  # noqa: E501

        :return: The last_instalment of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._last_instalment

    @last_instalment.setter
    def last_instalment(self, last_instalment):
        """Sets the last_instalment of this MutualFundSipData.

        Last triggered instalment timestamp.  # noqa: E501

        :param last_instalment: The last_instalment of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._last_instalment = last_instalment

    @property
    def pending_instalments(self):
        """Gets the pending_instalments of this MutualFundSipData.  # noqa: E501

        Pending instalments when applicable.  # noqa: E501

        :return: The pending_instalments of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._pending_instalments

    @pending_instalments.setter
    def pending_instalments(self, pending_instalments):
        """Sets the pending_instalments of this MutualFundSipData.

        Pending instalments when applicable.  # noqa: E501

        :param pending_instalments: The pending_instalments of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._pending_instalments = pending_instalments

    @property
    def instalment_day(self):
        """Gets the instalment_day of this MutualFundSipData.  # noqa: E501

        Day of month for monthly SIPs when applicable.  # noqa: E501

        :return: The instalment_day of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._instalment_day

    @instalment_day.setter
    def instalment_day(self, instalment_day):
        """Sets the instalment_day of this MutualFundSipData.

        Day of month for monthly SIPs when applicable.  # noqa: E501

        :param instalment_day: The instalment_day of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._instalment_day = instalment_day

    @property
    def completed_instalments(self):
        """Gets the completed_instalments of this MutualFundSipData.  # noqa: E501

        Completed instalment count when available.  # noqa: E501

        :return: The completed_instalments of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._completed_instalments

    @completed_instalments.setter
    def completed_instalments(self, completed_instalments):
        """Sets the completed_instalments of this MutualFundSipData.

        Completed instalment count when available.  # noqa: E501

        :param completed_instalments: The completed_instalments of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._completed_instalments = completed_instalments

    @property
    def trigger_price(self):
        """Gets the trigger_price of this MutualFundSipData.  # noqa: E501

        Trigger price when applicable.  # noqa: E501

        :return: The trigger_price of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._trigger_price

    @trigger_price.setter
    def trigger_price(self, trigger_price):
        """Sets the trigger_price of this MutualFundSipData.

        Trigger price when applicable.  # noqa: E501

        :param trigger_price: The trigger_price of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._trigger_price = trigger_price

    @property
    def sip_type(self):
        """Gets the sip_type of this MutualFundSipData.  # noqa: E501

        SIP channel/type (e.g. sip, amc_sip).  # noqa: E501

        :return: The sip_type of this MutualFundSipData.  # noqa: E501
        :rtype: object
        """
        return self._sip_type

    @sip_type.setter
    def sip_type(self, sip_type):
        """Sets the sip_type of this MutualFundSipData.

        SIP channel/type (e.g. sip, amc_sip).  # noqa: E501

        :param sip_type: The sip_type of this MutualFundSipData.  # noqa: E501
        :type: object
        """

        self._sip_type = sip_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MutualFundSipData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MutualFundSipData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
