# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PaymentHistoryData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'object',
        'mode': 'object',
        'status': 'object',
        'reason': 'object',
        'last_updated_at': 'object',
        'bank_name': 'object',
        'transaction_id': 'object',
        'total_charges': 'object',
        'charges_category': 'object'
    }

    attribute_map = {
        'amount': 'amount',
        'mode': 'mode',
        'status': 'status',
        'reason': 'reason',
        'last_updated_at': 'last_updated_at',
        'bank_name': 'bank_name',
        'transaction_id': 'transaction_id',
        'total_charges': 'total_charges',
        'charges_category': 'charges_category'
    }

    def __init__(self, amount=None, mode=None, status=None, reason=None, last_updated_at=None, bank_name=None, transaction_id=None, total_charges=None, charges_category=None):  # noqa: E501
        """PaymentHistoryData - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._mode = None
        self._status = None
        self._reason = None
        self._last_updated_at = None
        self._bank_name = None
        self._transaction_id = None
        self._total_charges = None
        self._charges_category = None
        self.discriminator = None
        if amount is not None:
            self.amount = amount
        if mode is not None:
            self.mode = mode
        if status is not None:
            self.status = status
        if reason is not None:
            self.reason = reason
        if last_updated_at is not None:
            self.last_updated_at = last_updated_at
        if bank_name is not None:
            self.bank_name = bank_name
        if transaction_id is not None:
            self.transaction_id = transaction_id
        if total_charges is not None:
            self.total_charges = total_charges
        if charges_category is not None:
            self.charges_category = charges_category

    @property
    def amount(self):
        """Gets the amount of this PaymentHistoryData.  # noqa: E501


        :return: The amount of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this PaymentHistoryData.


        :param amount: The amount of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._amount = amount

    @property
    def mode(self):
        """Gets the mode of this PaymentHistoryData.  # noqa: E501


        :return: The mode of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this PaymentHistoryData.


        :param mode: The mode of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._mode = mode

    @property
    def status(self):
        """Gets the status of this PaymentHistoryData.  # noqa: E501


        :return: The status of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PaymentHistoryData.


        :param status: The status of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._status = status

    @property
    def reason(self):
        """Gets the reason of this PaymentHistoryData.  # noqa: E501


        :return: The reason of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this PaymentHistoryData.


        :param reason: The reason of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._reason = reason

    @property
    def last_updated_at(self):
        """Gets the last_updated_at of this PaymentHistoryData.  # noqa: E501


        :return: The last_updated_at of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._last_updated_at

    @last_updated_at.setter
    def last_updated_at(self, last_updated_at):
        """Sets the last_updated_at of this PaymentHistoryData.


        :param last_updated_at: The last_updated_at of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._last_updated_at = last_updated_at

    @property
    def bank_name(self):
        """Gets the bank_name of this PaymentHistoryData.  # noqa: E501


        :return: The bank_name of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._bank_name

    @bank_name.setter
    def bank_name(self, bank_name):
        """Sets the bank_name of this PaymentHistoryData.


        :param bank_name: The bank_name of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._bank_name = bank_name

    @property
    def transaction_id(self):
        """Gets the transaction_id of this PaymentHistoryData.  # noqa: E501


        :return: The transaction_id of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this PaymentHistoryData.


        :param transaction_id: The transaction_id of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._transaction_id = transaction_id

    @property
    def total_charges(self):
        """Gets the total_charges of this PaymentHistoryData.  # noqa: E501


        :return: The total_charges of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._total_charges

    @total_charges.setter
    def total_charges(self, total_charges):
        """Sets the total_charges of this PaymentHistoryData.


        :param total_charges: The total_charges of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._total_charges = total_charges

    @property
    def charges_category(self):
        """Gets the charges_category of this PaymentHistoryData.  # noqa: E501


        :return: The charges_category of this PaymentHistoryData.  # noqa: E501
        :rtype: object
        """
        return self._charges_category

    @charges_category.setter
    def charges_category(self, charges_category):
        """Sets the charges_category of this PaymentHistoryData.


        :param charges_category: The charges_category of this PaymentHistoryData.  # noqa: E501
        :type: object
        """

        self._charges_category = charges_category

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentHistoryData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentHistoryData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
