# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SearchPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'page_number': 'object',
        'total_pages': 'object',
        'records': 'object',
        'total_records': 'object'
    }

    attribute_map = {
        'page_number': 'page_number',
        'total_pages': 'total_pages',
        'records': 'records',
        'total_records': 'total_records'
    }

    def __init__(self, page_number=None, total_pages=None, records=None, total_records=None):  # noqa: E501
        """SearchPage - a model defined in Swagger"""  # noqa: E501
        self._page_number = None
        self._total_pages = None
        self._records = None
        self._total_records = None
        self.discriminator = None
        if page_number is not None:
            self.page_number = page_number
        if total_pages is not None:
            self.total_pages = total_pages
        if records is not None:
            self.records = records
        if total_records is not None:
            self.total_records = total_records

    @property
    def page_number(self):
        """Gets the page_number of this SearchPage.  # noqa: E501


        :return: The page_number of this SearchPage.  # noqa: E501
        :rtype: object
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this SearchPage.


        :param page_number: The page_number of this SearchPage.  # noqa: E501
        :type: object
        """

        self._page_number = page_number

    @property
    def total_pages(self):
        """Gets the total_pages of this SearchPage.  # noqa: E501


        :return: The total_pages of this SearchPage.  # noqa: E501
        :rtype: object
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages):
        """Sets the total_pages of this SearchPage.


        :param total_pages: The total_pages of this SearchPage.  # noqa: E501
        :type: object
        """

        self._total_pages = total_pages

    @property
    def records(self):
        """Gets the records of this SearchPage.  # noqa: E501


        :return: The records of this SearchPage.  # noqa: E501
        :rtype: object
        """
        return self._records

    @records.setter
    def records(self, records):
        """Sets the records of this SearchPage.


        :param records: The records of this SearchPage.  # noqa: E501
        :type: object
        """

        self._records = records

    @property
    def total_records(self):
        """Gets the total_records of this SearchPage.  # noqa: E501


        :return: The total_records of this SearchPage.  # noqa: E501
        :rtype: object
        """
        return self._total_records

    @total_records.setter
    def total_records(self, total_records):
        """Sets the total_records of this SearchPage.


        :param total_records: The total_records of this SearchPage.  # noqa: E501
        :type: object
        """

        self._total_records = total_records

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchPage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
