# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.analytics_data import AnalyticsData  # noqa: E501
from swagger_client.rest import ApiException


class TestAnalyticsData(unittest.TestCase):
    """AnalyticsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyticsData(self):
        """Test AnalyticsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.analytics_data.AnalyticsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
