# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import upstox_client
from upstox_client.api.order_controller_v_3_api import OrderApiV3  # noqa: E501
from upstox_client.rest import ApiException


class TestOrderApiV3(unittest.TestCase):
    """OrderApiV3 unit test stubs"""

    def setUp(self):
        self.api = OrderApiV3()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_order(self):
        """Test case for cancel_order

        """
        pass

    def test_modify_order(self):
        """Test case for modify_order

        """
        pass

    def test_place_order(self):
        """Test case for place_order

        """
        pass


if __name__ == '__main__':
    unittest.main()
