# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import upstox_client
from upstox_client.models.gtt_cancel_order_request import GttCancelOrderRequest  # noqa: E501
from upstox_client.rest import ApiException


class TestGttCancelOrderRequest(unittest.TestCase):
    """GttCancelOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGttCancelOrderRequest(self):
        """Test GttCancelOrderRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = upstox_client.models.gtt_cancel_order_request.GttCancelOrderRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
