# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.put_call_option_chain_data import PutCallOptionChainData  # noqa: E501
from swagger_client.rest import ApiException


class TestPutCallOptionChainData(unittest.TestCase):
    """PutCallOptionChainData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutCallOptionChainData(self):
        """Test PutCallOptionChainData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.put_call_option_chain_data.PutCallOptionChainData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
