# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import upstox_client
from upstox_client.models.indie_user_init_token_response import IndieUserInitTokenResponse  # noqa: E501
from upstox_client.rest import ApiException


class TestIndieUserInitTokenResponse(unittest.TestCase):
    """IndieUserInitTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndieUserInitTokenResponse(self):
        """Test IndieUserInitTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = upstox_client.models.indie_user_init_token_response.IndieUserInitTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
