# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.multi_order_request import MultiOrderRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestMultiOrderRequest(unittest.TestCase):
    """MultiOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiOrderRequest(self):
        """Test MultiOrderRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.multi_order_request.MultiOrderRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
