# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.post_trade_api import PostTradeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPostTradeApi(unittest.TestCase):
    """PostTradeApi unit test stubs"""

    def setUp(self):
        self.api = PostTradeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_trades_by_date_range(self):
        """Test case for test_get_trades_by_date_range

        """
        pass


if __name__ == '__main__':
    unittest.main()
